### ISSUE TITLE
Configuration Help - Farenheit and "Smaller" Cities

### ISSUE THREAD

**Issue by tedtms** [adafruit/esp8266-weather-station-color#4]
This is a great project! Thanks for making it more accessible using Adafruit's components! I have a couple questions though about the system configuration:

1. Is it possible to configure the display for Fahrenheit?
2. I'm only able to get the system to work for "major" cities. For example, I live in Michigan and want to pull data for my hometown, but the station can only pull data if I configure it for Detroit.

Regarding #2, I find it really frustrating because the OpenWeather API provides the current conditions and 5-day forecast for other cities if manually polled, without issues. The data structure is the same as would be present if I pulled it for Detroit. Has anyone encountered this before?

**Comment by caternuson** [comment]
For 1, update `settings.h` and recompile/upload the sketch. Units are set here:
https://github.com/adafruit/esp8266-weather-station-color/blob/6e5c553ac6b9111d7aa1260d064104704479f7e0/settings.h#L47


For 2, more complex. City ID used to be the only way to specify location. Looks like that is being deprecated in favor of lat/lon.

https://openweathermap.org/current#geocoding

> **Please note that buit-in API requests by city name, zip-codes and city id will be deprecated soon.**

This code would need to be re-written to accommodate that.

**Comment by tedtms** [comment]
Thanks for the reply!! Are there plans to update the codebase to work with lat/lon?

**Comment by caternuson** [comment]
Closing this issue in favor of #5 to track necessary changes to keep up with API changes.
